EXPERIMENT: baseline_epoch_80000_full_triplet
CUDA_VISIBLE_DEVICES: ' 2'
TRAIN:
  RECORD_STEP: 5000
  DISPLAY_INFO_STEP: 2500
  MAX_ITERS: 80000
  TRIPLET_LOSS:
    TYPE: full
    MARGIN: 0.2
TEST:
  TEST_ITER: 80000