PATH:
  EXPERIMENT_DIR: train_256_with_ce_full_10_no_fancy_sce_lrs_added_no_warmup
MODEL:
  BNNECK: True
  DEVICE_ID: "'4'"
  CE_DIVIDED: 1
TRAIN:
  USE_SCHEDULER: False
  CACHE: False
SOLVER:
  OPTIMIZER_MANNER: whole-model
DATASET:
  NUM_WORKERS: 8