EXPERIMENT: relu_epoch_80000_full_triplet
CUDA_VISIBLE_DEVICES: ' 4'
TRAIN:
  RECORD_STEP: 5000
  DISPLAY_INFO_STEP: 2500
  MAX_ITERS: 80000
  TRIPLET_LOSS:
    TYPE: full
    MARGIN: 0.2
MODEL:
  ACTIVATION: relu
TEST:
  TEST_ITER: 80000