EXPERIMENT: 512_features_epoch_130000_full_triplet
CUDA_VISIBLE_DEVICES: "'4,5'"
TRAIN:
  RECORD_STEP: 5000
  DISPLAY_INFO_STEP: 2500
  MAX_ITERS: 130000
  TRIPLET_LOSS:
    TYPE: full
    MARGIN: 0.2
MODEL:
  NUM_FEATURES: 512
TEST:
  TEST_ITER: 130000