PATH:
  EXPERIMENT_DIR: train_256_with_ce_full_1_no_fancy_sce_applied
MODEL:
  BNNECK: True
  DEVICE_ID: "'6'"
  CE_DIVIDED: 1
TRAIN:
  USE_SCHEDULER: False
  CACHE: False
SOLVER:
  OPTIMIZER_MANNER: whole-model