EXPERIMENT: 256_features_with_ce_epoch_80000_full_triplet
CUDA_VISIBLE_DEVICES: "'6, 7'"
TRAIN:
  RECORD_STEP: 5000
  DISPLAY_INFO_STEP: 2500
  MAX_ITERS: 80000
  TRIPLET_LOSS:
    TYPE: full
    MARGIN: 0.2
MODEL:
  NUM_FEATURES: 256
  BNNECK: True
TEST:
  TEST_ITER: 25000